switch(true) {
    case
     `type||typeof`:
    case
    `interface&&namespace`:
    case
    `extends//implements`:
    case
    `as\\infer`:
    case
    `ture!==false`:
    case
    `public||&private`:
    case
    `this&||super`:
    case
    'const&||&let':
    case
    `import===export`:
}
